/*** File generated by GenISSLib version 2.1: DO NOT MODIFY ***/
#ifndef __isa_tms320_unisim__component__cxx__processor__tms320__isa__tms320_HH__
#define __isa_tms320_unisim__component__cxx__processor__tms320__isa__tms320_HH__
#ifndef __STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS
#endif

#include <vector>
#include <inttypes.h>
#include <cstring>
namespace unisim { namespace component { namespace cxx { namespace processor { namespace tms320 { namespace isa { namespace tms320 {
typedef uint32_t CodeType;

template <
#line 45 "isa/tms320.isa"
class
#line 18 "isa_tms320.hh"
#line 45 "isa/tms320.isa"
CONFIG
#line 21 "isa_tms320.hh"
,
#line 45 "isa/tms320.isa"
bool
#line 25 "isa_tms320.hh"
#line 45 "isa/tms320.isa"
DEBUG
#line 28 "isa_tms320.hh"
>
class Operation;
const unsigned int NUM_OPERATIONS_PER_PAGE = 4096;
template <
#line 45 "isa/tms320.isa"
class
#line 35 "isa_tms320.hh"
#line 45 "isa/tms320.isa"
CONFIG
#line 38 "isa_tms320.hh"
,
#line 45 "isa/tms320.isa"
bool
#line 42 "isa_tms320.hh"
#line 45 "isa/tms320.isa"
DEBUG
#line 45 "isa_tms320.hh"
>
class DecodeMapPage
{
public:
	DecodeMapPage(typename CONFIG::address_t key);
	~DecodeMapPage();
	typename CONFIG::address_t key;
	DecodeMapPage *next;
	Operation<
#line 45 "isa/tms320.isa"
	CONFIG
#line 57 "isa_tms320.hh"
	,
#line 45 "isa/tms320.isa"
	DEBUG
#line 61 "isa_tms320.hh"
	> *operation[NUM_OPERATIONS_PER_PAGE];
};

template <
#line 45 "isa/tms320.isa"
class
#line 68 "isa_tms320.hh"
#line 45 "isa/tms320.isa"
CONFIG
#line 71 "isa_tms320.hh"
,
#line 45 "isa/tms320.isa"
bool
#line 75 "isa_tms320.hh"
#line 45 "isa/tms320.isa"
DEBUG
#line 78 "isa_tms320.hh"
>
class DecodeTableEntry
{
public:
	DecodeTableEntry(CodeType opcode, CodeType opcode_mask, Operation<
#line 45 "isa/tms320.isa"
	CONFIG
#line 86 "isa_tms320.hh"
	,
#line 45 "isa/tms320.isa"
	DEBUG
#line 90 "isa_tms320.hh"
	> *(*decode)(CodeType, typename CONFIG::address_t));
	CodeType opcode;
	CodeType opcode_mask;
	Operation<
#line 45 "isa/tms320.isa"
	CONFIG
#line 97 "isa_tms320.hh"
	,
#line 45 "isa/tms320.isa"
	DEBUG
#line 101 "isa_tms320.hh"
	> *(*decode)(CodeType code, typename CONFIG::address_t addr);
};
const unsigned int NUM_DECODE_HASH_TABLE_ENTRIES = 4096;
template <
#line 45 "isa/tms320.isa"
class
#line 108 "isa_tms320.hh"
#line 45 "isa/tms320.isa"
CONFIG
#line 111 "isa_tms320.hh"
,
#line 45 "isa/tms320.isa"
bool
#line 115 "isa_tms320.hh"
#line 45 "isa/tms320.isa"
DEBUG
#line 118 "isa_tms320.hh"
>
class Decoder
{
public:
	Decoder();
	virtual ~Decoder();

	Operation<
#line 45 "isa/tms320.isa"
	CONFIG
#line 129 "isa_tms320.hh"
	,
#line 45 "isa/tms320.isa"
	DEBUG
#line 133 "isa_tms320.hh"
	>*NCDecode(typename CONFIG::address_t addr);
	Operation<
#line 45 "isa/tms320.isa"
	CONFIG
#line 138 "isa_tms320.hh"
	,
#line 45 "isa/tms320.isa"
	DEBUG
#line 142 "isa_tms320.hh"
	> *NCDecode(typename CONFIG::address_t addr, CodeType code);
	Operation<
#line 45 "isa/tms320.isa"
	CONFIG
#line 147 "isa_tms320.hh"
	,
#line 45 "isa/tms320.isa"
	DEBUG
#line 151 "isa_tms320.hh"
	> *Decode(typename CONFIG::address_t addr);
	Operation<
#line 45 "isa/tms320.isa"
	CONFIG
#line 156 "isa_tms320.hh"
	,
#line 45 "isa/tms320.isa"
	DEBUG
#line 160 "isa_tms320.hh"
	> *Decode(typename CONFIG::address_t addr, CodeType insn);
	std::vector<DecodeTableEntry<
#line 45 "isa/tms320.isa"
	CONFIG
#line 165 "isa_tms320.hh"
	,
#line 45 "isa/tms320.isa"
	DEBUG
#line 169 "isa_tms320.hh"
	> > const& GetDecodeTable() const { return decode_table; };
	virtual void Fetch(void *, typename CONFIG::address_t, uint32_t) ;
	void InvalidateDecodingCacheEntry(typename CONFIG::address_t addr);
	void InvalidateDecodingCache();

	void SetLittleEndian();
	void SetBigEndian();
private:
	bool little_endian;
	std::vector<DecodeTableEntry<
#line 45 "isa/tms320.isa"
	CONFIG
#line 182 "isa_tms320.hh"
	,
#line 45 "isa/tms320.isa"
	DEBUG
#line 186 "isa_tms320.hh"
	> > decode_table;
	DecodeMapPage<
#line 45 "isa/tms320.isa"
	CONFIG
#line 191 "isa_tms320.hh"
	,
#line 45 "isa/tms320.isa"
	DEBUG
#line 195 "isa_tms320.hh"
	> *mru_page;
	DecodeMapPage<
#line 45 "isa/tms320.isa"
	CONFIG
#line 200 "isa_tms320.hh"
	,
#line 45 "isa/tms320.isa"
	DEBUG
#line 204 "isa_tms320.hh"
	> *decode_hash_table[NUM_DECODE_HASH_TABLE_ENTRIES];
	DecodeMapPage<
#line 45 "isa/tms320.isa"
	CONFIG
#line 209 "isa_tms320.hh"
	,
#line 45 "isa/tms320.isa"
	DEBUG
#line 213 "isa_tms320.hh"
	> *FindPage(typename CONFIG::address_t page_key)
#if defined(__GNUC__) && (__GNUC__ >= 3 && (__GNUC__ != 3 || __GNUC_MINOR__ != 4 || __GNUC_PATCHLEVEL__ != 6))
	__attribute__((always_inline))
#endif
	;
};

} } } } } } }
#line 47 "isa/tms320.isa"

#include <iosfwd>

/* code to be inserted at the declaration of the library */

/* Forward declaration of the cpu */
namespace unisim {
	namespace component {
		namespace cxx {
			namespace processor {
				namespace tms320 {

					template<class CONFIG, bool DEBUG>
					class CPU;

				} // end of namespace tms320
			} // end of namespace processor
		} // end of namespace cxx
	} // end of namespace component
} // end of namespace unisim

#line 244 "isa_tms320.hh"
namespace unisim { namespace component { namespace cxx { namespace processor { namespace tms320 { namespace isa { namespace tms320 {
template <
#line 45 "isa/tms320.isa"
class
#line 249 "isa_tms320.hh"
#line 45 "isa/tms320.isa"
CONFIG
#line 252 "isa_tms320.hh"
,
#line 45 "isa/tms320.isa"
bool
#line 256 "isa_tms320.hh"
#line 45 "isa/tms320.isa"
DEBUG
#line 259 "isa_tms320.hh"
>
class Operation
{
public:
	Operation(CodeType code, typename CONFIG::address_t addr, const char *name);
	virtual ~Operation();
	inline typename CONFIG::address_t GetAddr() const { return addr; }
	inline CodeType GetEncoding() const { return encoding; }
	inline const char *GetName() const { return name; }
	virtual
#line 40 "/local/home/gmouchard/unisim/svn/devel/unisim_lib/unisim/component/cxx/processor/tms320/isa/actions_dec.isa"
	void
#line 272 "isa_tms320.hh"
	disasm(
#line 40 "/local/home/gmouchard/unisim/svn/devel/unisim_lib/unisim/component/cxx/processor/tms320/isa/actions_dec.isa"
	CPU<CONFIG, DEBUG> &
#line 276 "isa_tms320.hh"
#line 40 "/local/home/gmouchard/unisim/svn/devel/unisim_lib/unisim/component/cxx/processor/tms320/isa/actions_dec.isa"
	cpu
#line 279 "isa_tms320.hh"
	,
#line 40 "/local/home/gmouchard/unisim/svn/devel/unisim_lib/unisim/component/cxx/processor/tms320/isa/actions_dec.isa"
	std::ostream &
#line 283 "isa_tms320.hh"
#line 40 "/local/home/gmouchard/unisim/svn/devel/unisim_lib/unisim/component/cxx/processor/tms320/isa/actions_dec.isa"
	os
#line 286 "isa_tms320.hh"
	);
	virtual
#line 36 "/local/home/gmouchard/unisim/svn/devel/unisim_lib/unisim/component/cxx/processor/tms320/isa/actions_dec.isa"
	void
#line 291 "isa_tms320.hh"
	execute(
#line 36 "/local/home/gmouchard/unisim/svn/devel/unisim_lib/unisim/component/cxx/processor/tms320/isa/actions_dec.isa"
	CPU<CONFIG, DEBUG> &
#line 295 "isa_tms320.hh"
#line 36 "/local/home/gmouchard/unisim/svn/devel/unisim_lib/unisim/component/cxx/processor/tms320/isa/actions_dec.isa"
	cpu
#line 298 "isa_tms320.hh"
	);
protected:
	CodeType encoding;
	typename CONFIG::address_t addr;
	const char *name;
};

} } } } } } }
#endif
