/*** File generated by GenISSLib version 2.1: DO NOT MODIFY ***/
#ifndef ___local_home_gracia_svn_unisim_devel_unisim_lib_unisim_component_cxx_processor_powerpc_powerpc_unisim__component__cxx__processor__powerpc_HH__
#define ___local_home_gracia_svn_unisim_devel_unisim_lib_unisim_component_cxx_processor_powerpc_powerpc_unisim__component__cxx__processor__powerpc_HH__
#ifndef __STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS
#endif

#include <vector>
#include <inttypes.h>
namespace unisim { namespace component { namespace cxx { namespace processor { namespace powerpc {
typedef uint32_t CodeType;

template <
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
class
#line 17 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
CONFIG
#line 20 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
>
class Operation;
const unsigned int NUM_OPERATIONS_PER_PAGE = 4096;
template <
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
class
#line 27 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
CONFIG
#line 30 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
>
class DecodeMapPage
{
public:
	DecodeMapPage(typename CONFIG::address_t key);
	~DecodeMapPage();
	typename CONFIG::address_t key;
	DecodeMapPage *next;
	Operation<
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	CONFIG
#line 42 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	> *operation[NUM_OPERATIONS_PER_PAGE];
};

template <
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
class
#line 49 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
CONFIG
#line 52 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
>
class DecodeTableEntry
{
public:
	DecodeTableEntry(CodeType opcode, CodeType opcode_mask, Operation<
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	CONFIG
#line 60 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	> *(*decode)(CodeType, typename CONFIG::address_t));
	CodeType opcode;
	CodeType opcode_mask;
	Operation<
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	CONFIG
#line 67 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	> *(*decode)(CodeType code, typename CONFIG::address_t addr);
};
const unsigned int NUM_DECODE_HASH_TABLE_ENTRIES = 4096;
template <
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
class
#line 74 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
CONFIG
#line 77 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
>
class Decoder
{
public:
	Decoder();
	virtual ~Decoder();

	Operation<
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	CONFIG
#line 88 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	>*NCDecode(typename CONFIG::address_t addr);
	Operation<
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	CONFIG
#line 93 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	> *NCDecode(typename CONFIG::address_t addr, CodeType code);
	Operation<
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	CONFIG
#line 98 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	> *Decode(typename CONFIG::address_t addr);
	Operation<
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	CONFIG
#line 103 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	> *Decode(typename CONFIG::address_t addr, CodeType insn);
	std::vector<DecodeTableEntry<
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	CONFIG
#line 108 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	> > const& GetDecodeTable() const { return decode_table; };
	virtual void Fetch(void *, typename CONFIG::address_t, uint32_t) ;
	void InvalidateDecodingCacheEntry(typename CONFIG::address_t addr);
	void InvalidateDecodingCache();

	void SetLittleEndian();
	void SetBigEndian();
private:
	bool little_endian;
	std::vector<DecodeTableEntry<
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	CONFIG
#line 121 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	> > decode_table;
	DecodeMapPage<
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	CONFIG
#line 126 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	> *mru_page;
	DecodeMapPage<
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	CONFIG
#line 131 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	> *decode_hash_table[NUM_DECODE_HASH_TABLE_ENTRIES];
	DecodeMapPage<
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	CONFIG
#line 136 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	> *FindPage(typename CONFIG::address_t page_key)
#if defined(__GNUC__) && (__GNUC__ >= 3 && (__GNUC__ != 3 || __GNUC_MINOR__ != 4 || __GNUC_PATCHLEVEL__ != 6))
	__attribute__((always_inline))
#endif
	;
};

} } } } }
#line 40 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"

#include <unisim/component/cxx/processor/powerpc/cpu.hh>
#line 148 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_ppc.isa"


#include <stdarg.h>

namespace unisim {
	namespace component {
		namespace cxx {
			namespace processor {
				namespace powerpc {

					//typedef uint32_t registers_written_t;

#define RegNone					0x00000000
#define RegCTR					0x00000001
#define RegLR					0x00000002

					typedef uint32_t function_t;

#define FnInvalid				0x00000000
#define FnNop					0x00000001
#define FnIntBasic				0x00000002
#define FnIntBasicSerial			0x00000004
#define FnIntExtended				0x00000008
#define FnFpCommon				0x00000010
#define FnFpFPSCR				0x00000020
#define FnFpFPSCRSerial				0x00000040
#define FnCache					0x00000080
#define FnCacheSerial				0x00000100
#define FnBranch				0x00000200
#define FnConditionalBranch			0x00000400
#define FnBranchCountReg			0x00000800
#define FnBranchLinkReg				0x00001000
#define FnCondRegister				0x00002000
#define FnSysRegister				0x00004000
#define FnSysRegisterSerial			0x00008000
#define FnSysCall				0x00010000
#define FnMac					0x00020000

#define FnLoadInstruction			0x10000000
#define FnLoad					0x10000000
#define FnLoadByteReversed			0x11000000
#define FnLoadFloat				0x12000000
#define FnLoadMultiple				0x13000000
#define FnLoadMultipleRegList                   0x13100000
#define FnLoadString				0x14000000
#define FnLoadStringImm				0x15000000
#define FnLoadSerial				0x16000000

#define FnStore					0x20000000
#define FnStoreByteReversed			0x21000000
#define FnStoreFloat				0x22000000
#define FnStoreMultiple				0x23000000
#define FnStoreMultipleRegList                  0x23100000
#define FnStoreString				0x24000000
#define FnStoreStringImm			0x25000000
#define FnStoreSerial				0x26000000
#define FnDataCacheBA				0x27000000
#define FnDataCacheBF				0x28000000
#define FnDataCacheBI				0x29000000

					//STF
#define FnAccelerator				0x40000000
#define FnAcceleratorInit			0x40000001
#define FnAcceleratorMTA			0x40000002
#define FnAcceleratorMFA			0x40000003
					//EOSTF

#define FnPrefetchLoad                          0x80000000

					static char *get_function_name(function_t fn)
					{ static char buffer[256];
						char *buf = buffer;
						*buf = 0;
						if(!fn) buf += sprintf(buf, "FnInvalid");
						else    buf += sprintf(buf, "FnValid");
						return buffer;
					}

				} // end of namespace powerpc
			} // end of namespace processor
		} // end of namespace cxx
	} // end of namespace component
} // end of namespace unisim

#line 234 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 37 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_latencies.isa"


namespace unisim {
	namespace component {
		namespace cxx {
			namespace processor {
				namespace powerpc {


					typedef unsigned int latencies_t[8];
#define LAT(lat) (Operation<CONFIG>::latencies[Operation<CONFIG>::nstages++] = (lat), Operation<CONFIG>::latency += (lat))

				} // end of namespace powerpc
			} // end of namespace processor
		} // end of namespace cxx
	} // end of namespace component
} // end of namespace unisim

#line 254 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 66 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_dependencies.isa"


namespace unisim {
	namespace component {
		namespace cxx {
			namespace processor {
				namespace powerpc {


#include <stdarg.h>

					// DD New depencies are arriving ...
					/*
					typedef enum operand_type_t { GPR_T, FPR_T, CRF_T, CRB_T, FPSCRF_T,
						SR_T, CR_T , BO_T, BD_T, IMM_T, NONE_REGISTER} operand_type_t;
					*/
					/* New operand types for superscalar simulator... */
					typedef enum operand_type_t { GPR_T, FPR_T, CRF_T, CRB_T, FPSCRF_T, SR_T, BO_T, BD_T, IMM_T,
						CR_T, FPSCR_T, LR_T, CTR_T, XER_T, NONE_REGISTER} operand_type_t;


					typedef enum operand_direction_t { INPUT_T, OUTPUT_T } operand_direction_t;

					typedef struct operand_t
					{
						operand_type_t type;
						operand_direction_t dir;
						int value;
						struct operand_t *next;
					} operand_t;


#define INPUT(_type, _value) \
					{\
						Operation<CONFIG>::operands[Operation<CONFIG>::noperands].type = _type;\
						Operation<CONFIG>::operands[Operation<CONFIG>::noperands].dir = INPUT_T;\
						Operation<CONFIG>::operands[Operation<CONFIG>::noperands++].value = _value;\
					}

#define OUTPUT(_type, _value) \
					{\
						Operation<CONFIG>::operands[Operation<CONFIG>::noperands].type = _type;\
						Operation<CONFIG>::operands[Operation<CONFIG>::noperands].dir = OUTPUT_T;\
						Operation<CONFIG>::operands[Operation<CONFIG>::noperands++].value = _value;\
					}

					typedef operand_t operands_t[64];


				} // end of namespace powerpc
			} // end of namespace processor
		} // end of namespace cxx
	} // end of namespace component
} // end of namespace unisim

#line 311 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
namespace unisim { namespace component { namespace cxx { namespace processor { namespace powerpc {
template <
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
class
#line 316 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 38 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
CONFIG
#line 319 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
>
class Operation
{
public:
	Operation(CodeType code, typename CONFIG::address_t addr, const char *name);
	virtual ~Operation();
	inline typename CONFIG::address_t GetAddr() const { return addr; }
	inline CodeType GetEncoding() const { return encoding; }
	inline const char *GetName() const { return name; }
#line 127 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_ppc.isa"
	function_t function;
#line 331 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 57 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_latencies.isa"
	unsigned int latency;
#line 334 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 58 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_latencies.isa"
	int nstages;
#line 337 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 59 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_latencies.isa"
	latencies_t latencies;
#line 340 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 123 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_dependencies.isa"
	int noperands;
#line 343 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 124 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_dependencies.isa"
	operands_t operands;
#line 346 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	virtual
#line 758 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	bool
#line 350 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	is_sign_extended( );
	virtual
#line 745 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	bool
#line 355 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	load_need_conversion( );
	virtual
#line 733 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	bool
#line 360 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	store_need_conversion( );
	virtual
#line 707 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	uint32_t
#line 365 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	get_single(
#line 707 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	CPU<CONFIG> *
#line 369 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 707 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	cpu
#line 372 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	);
	virtual
#line 238 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	list <Operation<CONFIG> *>
#line 377 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	split_into( );
	virtual
#line 234 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	bool
#line 382 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	is_splitted( );
	virtual
#line 227 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	typename CONFIG::address_t
#line 387 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	loadstore_effective_address(
#line 227 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	CPU<CONFIG> *
#line 391 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 227 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	cpu
#line 394 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	);
	virtual
#line 209 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	int
#line 399 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	loadstore_string_numbyte(
#line 209 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	CPU<CONFIG> *
#line 403 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 209 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	cpu
#line 406 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	);
	virtual
#line 123 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	int
#line 411 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	memory_access_size( );
	virtual
#line 40 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	int
#line 416 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	loadstore_target_register(
#line 40 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	CPU<CONFIG> *
#line 420 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 40 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_load.isa"
	cpu
#line 423 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	);
	virtual
#line 120 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_branch.isa"
	bool
#line 428 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	branch_conditioned( );
	virtual
#line 100 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_branch.isa"
	bool
#line 433 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	branch_linked( );
	virtual
#line 68 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_branch.isa"
	bool
#line 438 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	branch_statically_predicted_taken(
#line 68 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_branch.isa"
	CPU<CONFIG> *
#line 442 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 68 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_branch.isa"
	cpu
#line 445 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	);
	virtual
#line 40 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_branch.isa"
	typename CONFIG::address_t
#line 450 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	get_target_address(
#line 40 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_branch.isa"
	typename CONFIG::address_t
#line 454 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 40 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_branch.isa"
	cia
#line 457 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	,
#line 40 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_branch.isa"
	CPU<CONFIG> *
#line 461 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 40 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/sim_branch.isa"
	cpu
#line 464 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	);
	virtual void initialize_operands( );
	virtual void initialize_latencies( );
	virtual void initialize_function( );
	virtual
#line 48 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	void
#line 472 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	disasm(
#line 48 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	CPU<CONFIG> *
#line 476 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 48 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	cpu
#line 479 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	,
#line 48 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	ostream&
#line 483 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 48 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	os
#line 486 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	);
	virtual
#line 44 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	void
#line 491 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	execute(
#line 44 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	CPU<CONFIG> *
#line 495 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
#line 44 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/ppc.isa"
	cpu
#line 498 "/local/home/gracia/svn/unisim/devel/unisim_lib/unisim/component/cxx/processor/powerpc/powerpc.hh"
	);
protected:
	CodeType encoding;
	typename CONFIG::address_t addr;
	const char *name;
};

} } } } }
#endif
