function (unisim__kernel__service SRCS INCDIR LIBS DEFS)
	stl_iostream ()
	stl_string ()
	stl_list ()
	stl_queue ()
	stl_map ()
	stl_vector ()
	stl_sstream ()
	clib_string_h ()
	stl_fstream ()
	clib_stdlib_h ()
	boost_graph ()
	libxml2 (LX2_INCDIR LX2_LIBS LX2_DEFS)
	unisim__kernel__logger ()
	set (${SRCS} unisim/kernel/service/service.cc
		unisim/kernel/service/service.hh
		unisim/kernel/service/xml_helper.cc
		unisim/kernel/service/xml_helper.hh PARENT_SCOPE)
	set (${INCDIR} ${LX2_INCDIR} PARENT_SCOPE)
	set (${LIBS} ${LX2_LIBS} PARENT_SCOPE)
	set (${DEFS} ${LX2_DEFS} PARENT_SCOPE)
endfunction (unisim__kernel__service SRCS)
